### ISSUE TITLE
Access Maximum Monthly Mean for each buoy

### ISSUE THREAD

**Issue by ericboucher** [oceansystems/aqualink-app#27]
Let's discuss how to get the maximum monthly mean temperature for each buoy location. This is super easy to get in the dataset available on NOAAs website but we don't currently have an API to query this programmatically.

Drew:
We can discuss the easiest way to do this. We could build a super lightweight api that queries based on lat/lon, and if we have that, we can add any climatology dataset to the api.

**Comment by ericboucher** [comment]
@drewjgray could you add the links to the relevant NOAA datasets here and share a bit more about your thoughts.

We can probably just create a super simple script that fetches data from NOAA and keeps the average temperature for each buoy over the past 12 months

**Comment by drewjgray** [comment]
Here is a link to the NOAA Climatology (historical) data: ftp://ftp.star.nesdis.noaa.gov/pub/sod/mecb/crw/data/5km/v3.1/nc/v1.0/daily/dhw/

The netcdf file has a band called MMM that is the pre-computed maximum monthly mean for each month. I am thinking we can write this file to the postgres db and build a simple API to grab the value based on lat/lon.
